### PR TITLE
update to upstream lz4 revision 130 and export the new compress_fast …

### PR DESCRIPTION
**Pull request by totaam**
as requested, here's the update and "compress_fast"

### CODE REVIEW

**Comment by steeve** [comment]
can you squash the commits into one please ? thanks
also, did the tests pass ?

**Comment by totaam** [comment]
I've tried, 5 times or more now.
None of the git instructions for squashing I have found on the interwebs work:
$ git reset --hard 
$ git rebase -i 8ac9cf9df8fb8d51f40a3065fa538f8df1c8a62a
(then change the second commit to a "squash")
$ git push origin master -f
Everything up-to-date
It shouldn't be that hard to squash 2 commits! (me going back to svn)

The tests did pass...

**Comment by jonathanunderwood** [comment]
IMO it's actually helpful and good practice to keep the version number update in a separate commit.

**Comment by totaam** [comment]
@jonathanunderwood I agree, except that in this case I've messed things up: I updated half in each commit...

**Comment by jonathanunderwood** [comment]
OK, I fixed it up for you here:

https://github.com/jonathanunderwood/python-lz4/commits/master

You might need to fork that repository and make a new pull request though - I can't see a way to change this pull request.

The way you tried to do it was correct. I suspect where you went wrong is in placing the "squash" next to the wrong commit. The commits are ordered with the oldest from at the top to the newest at the bottom when doing a rebase - that can be counterintuitive.

**Comment by jonathanunderwood** [comment]
On that branch I've further split the patchset into 3 logical chunks:

1) Update the bundled lz4 to r130
2) Export the fast_compress method from the python module
3) Bump release to 0.8

That'll make reviewing the changes simpler, and keep the history clean.

**Comment by jonathanunderwood** [comment]
I've now issued a separate pull request which splits these commits up logically as described.

**Pull request closed without merging**
