### PR TITLE
Add copyright headers to project specific code

### PR DESCRIPTION
**Pull request by vortechs2000**
Also referenced license in README

Used BSD 3-clause as requested by Steeve Morin

### CODE REVIEW

**Comment by vortechs2000** [comment]
Add copyright headers per issue #11.  The 3-clause BSD license was used with "Steeve Morin" replacing the organization in clause 3.  I also pointed the README at the 3-clause license in the Introduction section.

**Comment by alq666** [comment]
+1 for merge.

**Comment by steeve** [comment]
Thank you. Just got back from New Year vacation with very limited internet.

Anyway. Merged.

**Comment by vortechs2000** [comment]
Thanks Steeve - no worries, I was avoiding this kind of work all holiday break even though I _did_ have access to reasonable internet.  :)

**Pull request merged**
